# Generated by Django 3.2.6 on 2021-10-11 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0002_auto_20211011_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='phlebotomists',
            name='username',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='myapp1.users', to_field='username'),
            preserve_default=False,
        ),
    ]
